name: Android Debug APK Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    env:
      COMMIT_HASH: ${{ github.sha }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant permission to execute gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: List APK files
        run: ls -lh app/build/outputs/apk/debug/

      - name: Rename APK with commit hash
        run: |
          cp app/build/outputs/apk/debug/app-debug.apk app/debug-${COMMIT_HASH}.apk

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/debug-${{ env.COMMIT_HASH }}.apk
